---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      prometheus.io/scrape: "true"
      fabric8.io/scm-tag: HEAD
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/springboot-mysql-fabric-app
    labels:
      expose: "true"
      hystrix.enabled: "true"
      app: springboot-mysql-fabric-app
      provider: fabric8
      version: "1.0"
      group: com.sample
    name: springboot-mysql-fabric-app
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: springboot-mysql-fabric-app
      provider: fabric8
      group: com.sample
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=springboot-mysql-fabric-app&var-version=1.0
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/springboot-mysql-fabric-app
    labels:
      hystrix.enabled: "true"
      app: springboot-mysql-fabric-app
      provider: fabric8
      version: "1.0"
      group: com.sample
    name: springboot-mysql-fabric-app
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: springboot-mysql-fabric-app
        provider: fabric8
        group: com.sample
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=springboot-mysql-fabric-app&var-version=1.0
          fabric8.io/scm-tag: HEAD
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/springboot-mysql-fabric-app
        labels:
          hystrix.enabled: "true"
          app: springboot-mysql-fabric-app
          provider: fabric8
          version: "1.0"
          group: com.sample
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: springboot-mysql-fabric-app:1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
